### ISSUE TITLE
atm-cli on Windows 10: process didn't exit successfully

### ISSUE THREAD

**Issue by Adiaphon** [allthemusicllc/atm-cli#29]
Hi guys,

I followed your instructions in your readme.md. The test call `cargo run --release -- -h # show usage` succeeded but the example below always throws an error. Is this a known issue and does your tool support Windows 10?

```
λ cargo run --release -- single -n 'C:4,D:4,E:4,F:4,G:4,A:4,B:4,C:5' -t test.mid
    Finished release [optimized] target(s) in 0.10s
     Running `target\release\atm.exe single -n 'C:4,D:4,E:4,F:4,G:4,A:4,B:4,C:5' -t test.mid`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', lib\libatm\src\lib.rs:197:26
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:77
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libcore\fmt\mod.rs:1052
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\io\mod.rs:1426
   5: std::sys_common::backtrace::_print
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:204
   8: std::panicking::default_hook
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:224
   9: std::panicking::rust_panic_with_hook
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:472
  10: std::panicking::begin_panic_handler
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:380
  11: core::panicking::panic_fmt
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libcore\panicking.rs:85
  12: core::option::expect_none_failed
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libcore\option.rs:1199
  13: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  14: <libatm::MIDINoteSequence as core::str::FromStr>::from_str
  15: atm::directives::parse_sequence_argument
  16: <atm::directives::SingleDirectiveArgs as core::convert::From<&clap::args::arg_matches::ArgMatches>>::from
  17: atm::cli::Cli::run
  18: BITSET
  19: main
  20: std::rt::lang_start_internal::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\rt.rs:52
  21: std::panicking::try::do_call<closure-0,i32>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:305
  22: panic_unwind::__rust_maybe_catch_panic
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libpanic_unwind\lib.rs:86
  23: std::panicking::try
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:281
  24: std::panic::catch_unwind
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panic.rs:394
  25: std::rt::lang_start_internal
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\rt.rs:51
  26: main
  27: invoke_main
             at d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  28: __scrt_common_main_seh
             at d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  29: BaseThreadInitThunk
  30: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\release\atm.exe single -n 'C:4,D:4,E:4,F:4,G:4,A:4,B:4,C:5' -t test.mid` (exit code: 101)
```

**Comment by jmgbsas** [comment]
in windows 7 is the same, I use msys64 mingw64---
C:\RustWork\atm-cli\target\release>atm single -n 'C:4,D:4,E:4,F:4,G:4,A:4,B:4,
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', l
stack backtrace:
   0:           0x58a4bb - backtrace::backtrace::dbghelp::trace::ha09940ef4b8f
                               at C:\Users\runneradmin\.cargo\registry\src\git
ace/dbghelp.rs:88
   1:           0x58a4bb - backtrace::backtrace::trace_unsynchronized::h19d7d1
                               at C:\Users\runneradmin\.cargo\registry\src\git
ace/mod.rs:66
   2:           0x58a4bb - std::sys_common::backtrace::_print_fmt::hf038dfff95
                               at src\libstd\sys_common/backtrace.rs:78
   3:           0x58a4bb - <std::sys_common::backtrace::_print::DisplayBacktra
                               at src\libstd\sys_common/backtrace.rs:59
   4:           0x5b5e5c - core::fmt::write::h2e7468e40976ea37
                               at src\libcore\fmt/mod.rs:1076
   5:           0x57bb59 - std::io::Write::write_fmt::hef3158223e737cb6
                               at src\libstd\io/mod.rs:1537
   6:           0x58ecf0 - std::sys_common::backtrace::_print::he4a39cb956ba39
                               at src\libstd\sys_common/backtrace.rs:62
   7:           0x58ecf0 - std::sys_common::backtrace::print::h38d45a7d7a4d1f0
                               at src\libstd\sys_common/backtrace.rs:49
   8:           0x58ecf0 - std::panicking::default_hook::{{closure}}::hfcc0d2f
                               at src\libstd/panicking.rs:198
   9:           0x58e979 - std::panicking::default_hook::h7e61c8ee936a661d
                               at src\libstd/panicking.rs:217
  10:           0x58f42d - std::panicking::rust_panic_with_hook::h8b0608bd552a
                               at src\libstd/panicking.rs:526
  11:           0x58f044 - rust_begin_unwind
                               at src\libstd/panicking.rs:437
  12:           0x5b27a0 - core::panicking::panic_fmt::h858651244c7bf662
                               at src\libcore/panicking.rs:85
  13:           0x5b2403 - core::option::expect_none_failed::h5a48a85466a153d3
                               at src\libcore/option.rs:1269
  14:           0x4d61b8 - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>
  15:           0x4d3408 - <libatm::MIDINoteSequence as core::str::FromStr>::f
  16:           0x406dd6 - atm::directives::parse_sequence_argument::hca53acc0
  17:           0x406e99 - <atm::directives::SingleDirectiveArgs as core::conv
om::hbde1d1168ccf477c
  18:           0x403e73 - atm::cli::Cli::run::h5076cc473d683445
  19:           0x40153d - atm::main::he79edc519a9b1240
  20:           0x4015d6 - std::rt::lang_start::{{closure}}::h5a425375ac90732b
  21:           0x58f6ec - std::rt::lang_start_internal::{{closure}}::hcfe58f5
                               at src\libstd/rt.rs:52
  22:           0x58f6ec - std::panicking::try::do_call::hc4163588b8559d85
                               at src\libstd/panicking.rs:348
  23:           0x58f6ec - std::panicking::try::h310a3be58418d841
                               at src\libstd/panicking.rs:325
  24:           0x58f6ec - std::panic::catch_unwind::h52728a6ebc96df5e
                               at src\libstd/panic.rs:394
  25:           0x58f6ec - std::rt::lang_start_internal::ha1701ac7d300255b
                               at src\libstd/rt.rs:51
  26:           0x401588 - main
  27:           0x4013c1 - __tmainCRTStartup
                               at C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw
  28:           0x4014f6 - mainCRTStartup
                               at C:/_/M/mingw-w64-crt-git/src/mingw-w64/mingw
  29:         0x7751570d - units_search
  30:         0x7777385d - units_search

**Comment by allthemusicllc** [comment]
@Adiaphon can you try pulling from `master` and trying again? The CLI is slightly different now but this directive should work. Please let us know if this issue persists, we'll leave the issue open until you confirm it's working.

**Comment by jmgbsas** [comment]
For me the compialtion is ok run ok but windows media give me erro can nto toreproduce..
I did need to chnge  ' for  " in the example
C:\RustWork\atm-cli\target\release>atm gen single 'C:4,D:4,E:4,F:4,G:4,A:4,B:4,C:5' test.mid
error: Invalid value for '<notes>': Invalid note at index 0

C:\RustWork\atm-cli\target\release>atm gen tar-gz -p 2 'C:4,D:4,E:4,F:4,G:4,A:4,B:4,C:5' 8 C4_D4_E4_
error: Invalid value for '<notes>': Invalid note at index 0

C:\RustWork\atm-cli\target\release>atm gen single 'C:4,D:4,E:4,F:4,G:4,A:4,B:4,C:5' test.mid
error: Invalid value for '<notes>': Invalid note at index 0

C:\RustWork\atm-cli\target\release>atm gen single "C:4,D:4,E:4,F:4,G:4,A:4,B:4,C:5" test.mid
::: INFO: Generating MIDI file from pitch sequence
::: INFO: Attempting to write MIDI file to "test.mid"
::: INFO: Successfully wrote MIDI file
![imagen](https://user-images.githubusercontent.com/11756592/101289226-eedfb000-37d9-11eb-89e3-96e462d18a73.png)
Sublime Text show me 
![imagen](https://user-images.githubusercontent.com/11756592/101289247-0a4abb00-37da-11eb-94a9-5b1f7443b407.png)
Thanks

**Comment by meldaravaniel** [comment]
@jmgbsas at the risk of side-tracking...how do you actually get the "atm gen"  to run?  I've built and run the release, but running `atm help`  after that just gets me "command 'atm' not found" in WSL.  It's probably that there's a step X that I don't know about, but if so, I'd love to update the README to make it more user friendly.

**Comment by jmgbsas** [comment]
are you in windows? to me in the directory run ok 
Replace thecharacter ' (simpel quoted ) for double " ,, for windows is necesary...I do not like Posix I like native windows,,,WSL run in a  virtual machine and windows 10 too....hiper-V is a VM, I prefer run without WSL. I had windows10 in a disk but I deleted ,can not to test there I am in windows ultimate-.
![image](https://user-images.githubusercontent.com/11756592/102395052-64593680-3fb9-11eb-9eb7-7ab8ad149f50.png)

**Comment by jmgbsas** [comment]
I have this in my installation
![image](https://user-images.githubusercontent.com/11756592/102395327-bc903880-3fb9-11eb-9420-1e638a08377f.png)
and with which i found
C:\RustWork\atm-cli\target\release>which gcc
/mingw64/bin/gcc

C:\RustWork\atm-cli\target\release>which cargo
/c/Users/Jose/.cargo/bin/cargo

C:\RustWork\atm-cli\target\release>
I am using MSYS2 and I configured to rrun in Command prompt
 I can do it too with nim I download a project , With Rust there are other midi project ,see if they run ok for you,  after that come back to this.
